# Generated by Django 5.2.1 on 2026-05-15 11:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RugGeneration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("style", models.CharField(max_length=100)),
                ("size", models.CharField(max_length=50)),
                ("material", models.CharField(max_length=100)),
                ("colors", models.JSONField(default=list)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generated", "Generated"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="RoomPlacement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("selected_rug_index", models.IntegerField()),
                ("room_image_base64", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("placed", "Placed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("result_base64", models.TextField(blank=True)),
                ("shopify_product_id", models.CharField(blank=True, max_length=100)),
                ("shopify_variant_id", models.CharField(blank=True, max_length=100)),
                ("shopify_image_url", models.URLField(blank=True)),
                ("checkout_url", models.URLField(blank=True)),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="ruggen.ruggeneration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneratedRugImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                ("base64_data", models.TextField()),
                ("mime_type", models.CharField(default="image/jpeg", max_length=30)),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rug_images",
                        to="ruggen.ruggeneration",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
            },
        ),
    ]
