# Generated by Django 5.2.1 on 2026-06-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ruggen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "ruggen_generation_quota",
            },
        ),
    ]
