# Generated by Django 5.2.1 on 2026-06-25 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ruggen", "0002_generationquota"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationquota",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="generationquota",
            name="last_used",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
