# Generated by Django 5.2.1 on 2026-07-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ruggen", "0003_generationquota_created_at_generationquota_last_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="ruggeneration",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="generationquota",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
