# Generated by Django 5.2.1 on 2026-07-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ruggen", "0004_ruggeneration_email_alter_generationquota_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="ruggeneration",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ruggeneration",
            name="shape",
            field=models.CharField(default="rectangular", max_length=30),
        ),
    ]
