# Generated by Django 5.2.1 on 2026-07-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ruggen", "0005_ruggeneration_is_favorite_ruggeneration_shape"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ruggeneration",
            name="is_favorite",
        ),
        migrations.AddField(
            model_name="generatedrugimage",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
    ]
